### ISSUE TITLE
[FYI] The most recent release is 3.0.26 stable.

### ISSUE THREAD

**Issue by Atavic** [TriMoon/Privoxy#3]
See: https://www.privoxy.org/announce.txt

**Comment by TriMoon** [comment]
@Atavic , sorry for the late reply.
Yes i know im using that version also, and i'm on Linux nowerdays.
I actually forgot about this repo, it's totally outdated and i will be removing it soon anyway :rofl: 

I will have to backup some of the *.reg files though for historical config  :wink:
